baseURL: "https://jairomacedo.github.io/" 
title: Jairo Macedo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: Jairo_cv.pdf
       #   weight: 5 
        - name: Research
          url: papers/
          weight: 2
        - name: Portfolio
          url: courses/
      #    weight: 3
      #  - name: Data
      #    url: data/
      #    weight: 4 
       # - name: Blog
       #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: ""
    author: Jairo Macedo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jairo Macedo
          subtitle: "👋🏼 Hey, I’m Jairo! Be welcome.\n\n\n👨🏻‍💻 I’m an economist with a Master’s degree from UFPE."
          
          imageUrl: "profile.png"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Research
              url: papers/
            - name: Portfolio
              url: courses/
            - name: CV
              url: data/
           # - name: Books
           #   url: books/
           # - name: Tags
           #   url: tags/
           # - name: Archive
            #  url: archive/
           # - name: Blog
           #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Jairo_cv.pdf
        - name: Email
          url: jairo.macedo@ufpe.br
      #  - name: Zoom
      #    url: https://www.zoom.us/my/igelfeld
      #  - name: Location
      #    url: location/
      #  - name: Office Hours
      #    url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/jaairomacedo
       # - name: Substack
       #   url: https://pmichaillat.substack.com
       # - name: YouTube
       #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: X
          url: https://x.com/_jairo

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
