baseURL: "https://jairomacedo.github.io/" 
title: Jairo Macedo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
       # - name: CV
       #   url: Jairo_cv.pdf
       #   weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "👨🏻‍💻 I’m an economist with a Master’s degree from UFPE.

🔍 I’m interested in applied economics — especially causal inference in agriculture, misallocation, and corporate finance — and I like to spice things up with some macro modeling from time to time.

📚 I’m currently applying machine learning methods to problems in applied economics, with a focus on causal inference and forecasting.

💼 I’ve also worked in the corporate world, leading efforts in management, strategic planning, high-impact projects, and data-driven decision-making."
    author: Jairo Macedo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jairo Macedo
          subtitle: "I am a Professor in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: Jairo_cv.pdf
        - name: Email
          url: jairo.macedo@ufpe.br
      #  - name: Zoom
      #    url: https://www.zoom.us/my/igelfeld
      #  - name: Location
      #    url: location/
      #  - name: Office Hours
      #    url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/jaairomacedo
       # - name: Substack
       #   url: https://pmichaillat.substack.com
       # - name: YouTube
       #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: X
          url: https://x.com/_jairo

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
